# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
  - name: ENVVG
    displayName: Select Environment To Deploy
    type: string
    default: UAT
    values:
    - UAT
    #- PROD
 
trigger:
- main

# DEFINE VARIABLES
variables:
- name: build_agent_pool
  value: ubuntu-latest
- name: build_content_path
  value: "$(Build.SourcesDirectory)/dist/vids"

- name: env
  ${{ if eq(parameters.ENVVG, 'UAT') }}:
    value: uat
  ${{ if eq(parameters.ENVVG, 'PROD') }}:
    value: prod

- name: BACKEND_URL
  value: $(${{ parameters.ENVVG }}_BACKEND_URL)
             

- group: vids_group

stages:
  - stage: BUILD
    displayName: 'Build ${{ parameters.ENVVG }}'

    pool: 
      vmImage: $(build_agent_pool)
    jobs:
      - job: Build
        displayName: "Build UI"
        workspace:
          clean: all
        steps:
          - checkout: self     
  

          # Replace Variables & Tokens
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: 'Replace Tokens in Manifests'
            inputs:
              rootDirectory: '$(Build.SourcesDirectory)/src/environments/'
              targetFiles: 'environment.prod.ts, environment.ts'
              escapeType: none
              verbosity: detailed
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'

          - script: |
              npm install -g @angular/cli
              npm install
              ng build
            displayName: 'npm install and build'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(build_content_path)
              artifactName: build_ui_$(env)
            displayName: "Publish pipeline artifact" 
             
